### ISSUE TITLE
Can't run on my server

### ISSUE THREAD

**Issue by Kongchenglige** [Warriorrrr/GiantAI#1]
Hi, I use the [Kaiiju](https://github.com/KaiijuMC/Kaiiju)(modified folia) server, but when I try to summon a giant, it raises an error and can't work functionally, can you help me?
btw, if this plugin can add a function that allows giant spawn naturally, I will so appreciate it.

Kaiiju version: git-Kaiiju-"c2b7aec" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c2b7aec on ver/1.20.1)
Console log:
```
[00:27:29 ERROR]: Could not pass event EntityAddToWorldEvent to GiantAI v1.0.0
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R3/entity/CraftGiant
        at dev.warriorrr.giantai.GiantAI.on(GiantAI.java:37) ~[GiantAI-1.0.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor580.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:68) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2837) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2764) ~[?:?]
        at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:280) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:440) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.chunk.system.entity.EntityLookup.addNewEntity(EntityLookup.java:376) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1750) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1653) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:22) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:22) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tryAddFreshEntityWithPassengers(ServerLevel.java:1768) ~[?:?]
        at net.minecraft.server.commands.SummonCommand.lambda$createEntity$5(SummonCommand.java:73) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1513) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R3.entity.CraftGiant
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 30 more
```

**Comment by Warriorrrr** [comment]
Currently only 1.20.3+ is supported by the plugin since that was the latest version when I made it, you can either update your server or I can make a backport version if you want.

**Comment by Kongchenglige** [comment]
Due to the Kaiiju still stay at 1.20.1, if you can make a backport version I will so appreciate it.

**Comment by Warriorrrr** [comment]
Created a new branch for 1.20.1 which you can find [here](https://github.com/Warriorrrr/GiantAI/commit/df07786c71ac3329b03d82dbcab67f16195d4f66), not planning on making a new release for it but I compiled it for you here (as a zip since github doesn't like .jar files): [GiantAI-1.0.0.zip](https://github.com/Warriorrrr/GiantAI/files/14405292/GiantAI-1.0.0.zip). Hopefully this helps.
